### ISSUE TITLE
The downloaded gitstatusd binary should be saved to an arch specific name

### ISSUE THREAD

**Issue by krader1961** [href/elvish-gitstatus#10]
I sync my home directory (most of if it, anyway) to my other systems. The problem is that this elvish module saves the appropriate downloaded binary to *~/.elvish/package-data/gitstatusd*. This causes problems if that directory is shared by platforms that have different operating systems (such as macOS and Linux) or architectures (such as ppc and x86_64). The downloaded binary should include the OS and architecture in the filename it is saved to. Note that this is easier, and cheaper, to do now that we have `$platform:os` and `$platform:arch`.

**Comment by href** [comment]
I can sympathise with this, since I do the same. Though because I have a homogenous set of systems it didn't occur to me.

I think it makes sense to implement this. It's good timing too, because I have to rewrite the way binaries are updated due to https://github.com/romkatv/gitstatus/issues/33.

I kind of know what to do already, but haven't gotten around to it yet. For now, thanks for your report!

**Comment by krader1961** [comment]
That the author of `gitstatusd` doesn't consider backward compatibility with old clients important makes me do a /facepalm. At least they recognize that when they [say](https://github.com/romkatv/gitstatus/issues/33#issuecomment-498028759):

> The output format of gitstatusd is too primitive for any kind of backward compatibility...

What makes me sad is that the gitstatusd author doesn't recognize that even using its primitive binary format there is no reason backward compatibility can't be maintained. At least across most updates to that tool. Even worse is they think that simply forcing everyone to update in lockstep with their project updates, as discussed in [comment](https://github.com/romkatv/gitstatus/issues/33#issuecomment-498028759), is an acceptable strategy.

**Comment by href** [comment]
I pushed an update with 7487ad93ce1e459151e6a20468ad36a8a66b17d5 that gets the latest gitstatus release, using separate paths per OS and arch. Please have a look and let me know if it works for you (it does for me).

**Comment by krader1961** [comment]
Works for me, @href. Thanks for the fix.

**Comment by href** [comment]
You‘re welcome. Closing this issue.
