### ISSUE TITLE
Compatibility with current Elvish versions

### ISSUE THREAD

**Issue by krader1961** [href/elvish-gitstatus#13]
There have been some recent changes to Elvish that require updating this module. Specifically, `\` as a line continuation has been replaced by `^`. See https://elv.sh/blog/0.14.0-release-notes.html. While both are supported by anyone using the official 0.14 release anyone building from the master branch will see parse errors:

```
Exception: Multiple parse errors:
  should be '}'
    /Users/krader/.elvish/lib/github.com/href/elvish-gitstatus/gitstatus.elv, line 69:
          http-get https://raw.githubusercontent.com/romkatv/gitstatus/master/install.info \
  unexpected rune '\\'
    /Users/krader/.elvish/lib/github.com/href/elvish-gitstatus/gitstatus.elv, line 69:
          http-get https://raw.githubusercontent.com/romkatv/gitstatus/master/install.info \
Traceback:
  /Users/krader/.elvish/lib/github.com/zzamboni/elvish-themes/chain.elv, line 12:
    use github.com/href/elvish-gitstatus/gitstatus
  /Users/krader/.elvish/rc.elv, line 81:
    use github.com/zzamboni/elvish-themes/chain
```

**Comment by href** [comment]
Thanks, I kind of missed this, but @zzamboni was nice enough to provide a PR in the meantime: https://github.com/href/elvish-gitstatus/pull/12

So this should be fixed.
