### ISSUE TITLE
The gitstatusd installation fails on FreeBSD 11.1

### ISSUE THREAD

**Issue by krader1961** [href/elvish-gitstatus#14]
I recently attempted to use Elvish on FreeBSD 11.1 using the Elvish config I use on macOS. That config uses this module to display Git status in my prompt. On FreeBSD it fails with these errors:

```
???> tar: Error opening archive: Failed to open '/dev/sa0'
[prompt error] (curl exited with 23 | tar exited with 1)
see stack trace with "use exc; exc:show $edit:exceptions[0]"
```

The error is due to the `tar` in function `install` not explicitly specifying it should read from stdin. On most platforms reading from stdin is the default. On FreeBSD 11.1 the default is to read from */dev/sa0*. If you instead explicitly specify reading from stdin, by including `-f -` in the arguments to `tar`, it will work on all platforms.

I modified my local copy of this package and confirmed my proposed change works on macOS, FreeBSD, and Linux. That is,

```
http-get (download-url $version) | tar -x -z -C $appdir -f -
```

**Comment by href** [comment]
Thanks for your report, this should work now.
