### ISSUE TITLE
Update for V0.17

### ISSUE THREAD

**Issue by iandol** [href/elvish-gitstatus#17]
There are a couple of syntax changes that cause lots of deprecation warnings when running this module.

**Comment by href** [comment]
I'll look at it eventually, but I haven't upgraded yet and I'm not sure when I'll have the time.

Would be happy to accept a pull request.

**Comment by iandol** [comment]
Created https://github.com/href/elvish-gitstatus/pull/18

**Comment by href** [comment]
Cheers, merged.
