### ISSUE TITLE
Add compatibility with https://github.com/muesli/elvish-libs/blob/master/git.elv

### ISSUE THREAD

**Issue by href** [href/elvish-gitstatus#2]
The git:status command can be implemented to translate the return values of gitstatus:query

**Comment by zzamboni** [comment]
FWIW, the change is quite easy. I have an initial modified version of my `chain` theme which uses `gitstatus`: https://github.com/zzamboni/elvish-themes/blob/use-gitstatus/chain.org

One drawback at the moment is that `gitstatusd` does not seem to report deleted files separately, they are bundled together with "unstaged", so the `git-deleted` segment in my prompt theme is meaningless, I disabled it by default for now.

**Comment by zzamboni** [comment]
Something more - I am not sure anymore (even though I posted the initial comment about this) that trying to build a compatibility layer makes sense. `git:status` provides detailed information that is not available from `gitstatus`, such as the list of unstaged/deleted/untracked/etc files, and not just the count. Maybe keeping them fully separate is best to avoid confusion?

**Comment by href** [comment]
I came to the same conclusion when I looked at this again. `git:status` seems to be a superset of `gitstatus`, so I'm not sure this fits well. I'll keep this open in any case, because if there's a need for it, it would be quite simple to add.

**Comment by href** [comment]
Closed the wrong one.

**Comment by href** [comment]
I'm going to go ahead and close this one up. Feel free to reopen if you think this should still be implemented.
