### ISSUE TITLE
broken on ubuntu lts

### ISSUE THREAD

**Issue by jcarter3** [href/elvish-gitstatus#3]
I tried using zzamboni's chain them for elvish but ran into an issue with this module. I'm running ubuntu 18.04.3, and [line #217](https://github.com/href/elvish-gitstatus/blob/92eae8486e479340ff5662cb50fe3b37a965ccf6/gitstatus.elv#L217) fails with error:

`???> /bin/sh: 1: read: Illegal option -d
prompt function error: sh exited with 2`

zzamboni helped debug the issue and it seems that while on MacOS, `sh` will call bash, it does not on ubuntu. Changing that line to explicitly call bash fixed the error.

Though, with [this issue](https://github.com/elves/elvish/issues/885) being filed and implemented, updating to utilize the new functionality may be the best path forward.

**Comment by zzamboni** [comment]
@jcarter3 please note that #4 implements the change to use `read-upto` instead of the external call, please give it a try!

**Comment by jcarter3** [comment]
I tested this out, and it works! Thanks!

**Comment by href** [comment]
This should now work with `master`, so closing this.
