### ISSUE TITLE
prompt function error: want 0 arguments, got 1

### ISSUE THREAD

**Issue by href** [href/elvish-gitstatus#9]
This seems to be an issue with `elvish-gitstatus` and Elvish `HEAD`. Somewhat at random, the following error will pop up:

`prompt function error: want 0 arguments, got 1`

This cannot be reliably triggered and it is unclear what causes it, though it looks like a race-condition.

**Comment by href** [comment]
With the latest HEAD (https://github.com/elves/elvish/commit/41985123d3c3103619a6afc849ae58c4d95e1099), the error is now different and occurs much more frequently (to the point of being annoying):

    prompt function error: styled-text cannot be iterated

Do you see the same thing @zzamboni? @xiaq, any progress on some kind of tracing for Elvish?

**Comment by zzamboni** [comment]
I have not seen this specific error, but I have continued seeing the original one sporadically, particularly on large git repos when my machine is loaded, so I think it must be a race condition or timeout somewhere, but I still cannot pin it down.

**Comment by href** [comment]
Okay, the `prompt function error: styled-text cannot be iterated` error was due to the changes to `all`. I used to have the following stale transform (to keep the prompt *as is* until it changes):

```
edit:prompt-stale-transform = $all~
```

Changing it to the following made the error go away:
```
edit:prompt-stale-transform = [text]{
    put $text
}
```

This might have also solved my initial error, as I haven't seen the `prompt function error: want 0 arguments, got 1` in a bit, but since that error is somewhat random I'll have to wait and see.

**Comment by krader1961** [comment]
This bug is because `fn parse-response` is insufficiently paranoid. It can be called with an empty string because `x = ($get-response)` didn't get any data from gitstatusd because it died or the first byte read from the gitstatusd pipe was the `$rs` char.

**Comment by zzamboni** [comment]
@krader1961 I don't think this is the case. For one, in my tests I have modified `get-response` as follows:
```
fn get-response {
  echo "before" > /dev/tty
  read-upto $rs < $state[stdout]
  echo "after" > /dev/tty
}
```

And I see the following in the prompt, so I'm certain the error is being produced by the `read-upto` statement:
```
???> before
[prompt function error] arity mismatch: arguments here must be 0 values, but is 1 value
after
[~/D/P/w/learning-cfengine]─[⎇ master]─> 
```
Also, to test your theory I modified `parse-response` to explicitly deal with an empty argument, and I'm still seeing the error 😞

**Comment by zzamboni** [comment]
Thanks to great detective work from @xiaq, the cause of this error has been found: it's caused by a defective [stale prompt transformer](https://elv.sh/ref/edit.html#stale-prompt) function. Mine was:
```
edit:prompt-stale-transform = { each [x]{ styled $x[text] "gray" } }
```
But it turns out the stale transform function gets called with one argument (this apparently changed at some point) - this was the cause of the "expected 1, got 0 arguments" error. Rewriting the transformer like this eliminates the error (also, "gray" is no longer a valid color):
```
edit:prompt-stale-transform = [x]{ styled $x "bright-black" }
```

Thank you @krader1961 for your extensive investigation into this as well.

@href I believe this issue can now be closed.

**Comment by krader1961** [comment]
I agree with @zzamboni that this can be closed. While there are theoretical problems with this elvish module they might never happen in practice. In particular, the `parse-output` function should be more paranoid about the string it is handed. Still, it's hard to justify changing the code if no one can legitimately point to a case where the current behavior was insufficiently paranoid. And the problem that caused this issue to be opened is not such an example.

**Comment by href** [comment]
I shall go ahead and close this then. Thanks all for your input and glad it now works as expected.
